# Generated by Django 5.0.6 on 2024-06-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_delete_blogauthor_alter_author_bio_and_more'),
        ('blog', '0002_coverimage_blog_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_blogs', to='author.author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_cover_image', to='blog.coverimage'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='blog_tags', to='blog.tag'),
        ),
    ]
