# Generated by Django 5.0.6 on 2024-06-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_blogauthor_alter_author_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogAuthor',
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
